services:
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: "${GF_SERVER_ROOT_URL}"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "Keycloak"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "grafana"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid email profile"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "http://localhost:8080/realms/homelab/protocol/openid-connect/auth"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://keycloak:8080/realms/homelab/protocol/openid-connect/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "http://keycloak:8080/realms/homelab/protocol/openid-connect/userinfo"
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: "preferred_username"
      GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC: "true"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - homelab

volumes:
  grafana-data:

networks:
  homelab:
    external: true