services:
  gitea:
    image: gitea/gitea:1.21.0
    container_name: gitea
    environment:
      GITEA__server__ROOT_URL: "${GITEA__server__ROOT_URL}"
      GITEA__database__DB_TYPE: "${GITEA__database__DB_TYPE}"
    ports:
      - "3001:3000"
      - "2222:22"
    volumes:
      - gitea-data:/data
    networks:
      - homelab

volumes:
  gitea-data:

networks:
  homelab:
    external: true
