services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    ports:
      - "80:80"
      - "8888:8080"
    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - ./routes.yml:/routes.yml:ro
    networks:
      - homelab

networks:
  homelab:
    external: true