http:
  routers:
    grafana:
      rule: "Host(`grafana.localhost`)"
      service: grafana
      entryPoints:
        - web

    gitea:
      rule: "Host(`gitea.localhost`)"
      service: gitea
      entryPoints:
        - web

    keycloak:
      rule: "Host(`keycloak.localhost`)"
      service: keycloak
      entryPoints:
        - web

    nextcloud:
      rule: "Host(`nextcloud.localhost`)"
      service: nextcloud
      entryPoints:
        - web

    jellyfin:
      rule: "Host(`jellyfin.localhost`)"
      service: jellyfin
      entryPoints:
        - web

  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

    gitea:
      loadBalancer:
        servers:
          - url: "http://gitea:3000"

    keycloak:
      loadBalancer:
        servers:
          - url: "http://keycloak:8080"

    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud:80"

    jellyfin:
      loadBalancer:
        servers:
          - url: "http://jellyfin:8096"